### ISSUE TITLE
Can this work for jpeg or png images

### ISSUE THREAD

**Issue by hannadiamond** [lucasmansilla/multiatlas-rca#1]
Im trying to use this repo but it looks like it only supports nifit files. Is there a way to get it working for jpg or png files?

When trying to use regular png and jpg files, I get this error:

```
`Loading list of test images...
Loading Elastix registration parameters...
Building Multi-Atlas Segmentation model...
Building RCA Classifier...
Loop over test images...
1/34 Image filename: p4-6.png
  - Predicting segmentation...
Traceback (most recent call last):
  File "test.py", line 78, in <module>
    test_mas_rca(config)
  File "test.py", line 49, in test_mas_rca
    label, label_path, idxs = mas.predict_segmentation(
  File "/home/hanna/Downloads/seg_metrics/Multi-Atlas_RCA/models.py", line 44, in predict_segmentation
    idxs = self._atlas_selection(image_path)
  File "/home/hanna/Downloads/seg_metrics/Multi-Atlas_RCA/models.py", line 81, in _atlas_selection
    sitk.ReadImage(atlas_image) / 255.)))
  File "/home/hanna/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 4421, in __truediv__
    return DivideReal( self, float(other) )
  File "/home/hanna/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 27716, in DivideReal
    return _SimpleITK.DivideReal(*args)
RuntimeError: Exception thrown in SimpleITK DivideReal: /home/francesco/SimpleElastix/Code/Common/include/sitkMemberFunctionFactory.hxx:208:
sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 2D byN3itk6simple21DivideRealImageFilterE
`
```

@lucasmansilla

**Comment by lucasmansilla** [comment]
Hi @hdiggins,

The code works with png images. In fact, it was tested with that image format. About the reported error, I have just uploaded some changes to fix and improve the image loading. 

Sorry for the delay.

**Comment by hannadiamond** [comment]
@lucasmansilla Thanks for the update. I am now running into a few other errors but it only occurs for some of the training images. Do you know why this would be happening?

Error 1:
```
Traceback (most recent call last):
  File "test.py", line 76, in <module>
    test_mas_rca(config)
  File "test.py", line 47, in test_mas_rca
    dice = rca.predict_dice({
  File "/home/hanna/Downloads/seg_metrics/Multi-Atlas_RCA/models.py", line 33, in predict_dice
    scores.append(dsc(utils.load_image_itk(atlas_label),
  File "/home/hanna/Downloads/seg_metrics/Multi-Atlas_RCA/binary_metrics.py", line 24, in dsc
    lom_filter.Execute(result_bin, reference_bin)
  File "/home/hanna/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 44273, in Execute
    return _SimpleITK.LabelOverlapMeasuresImageFilter_Execute(self, image1, image2)
RuntimeError: Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /home/francesco/SimpleElastix/build/ITK-prefix/include/ITK-5.1/itkImageToImageFilter.hxx:220:
itk::ERROR: LabelOverlapMeasuresImageFilter(0x55de5526ac20): Inputs do not occupy the same physical space! 
InputImage Spacing: [1.0000000e+00, 1.0000000e+00], InputImage_1 Spacing: [3.5277778e-01, 3.5277778e-01]
	Tolerance: 1.0000000e-06
```
Error 2:
```
Exception thrown in SimpleITK LabelOverlapMeasuresImageFilter_Execute: /home/francesco/SimpleElastix/build/ITK/Modules/Core/Common/src/itkDataObject.cxx:355:
Requested region is (at least partially) outside the largest possible region.
```

Also, for predicting dice scores, it seems to take a bit under 1 second to compare a test image with a single training image. Is there a way to speed this up? Would reducing the image sizes of both increase speed?

**Comment by lucasmansilla** [comment]
Hi @hdiggins,

It seems that registration is not being accurate enough in aligning the images and this could be reflected in the predicted segmentation. Can you share the images and Elastix parameter files to reproduce the problem?

**Comment by hannadiamond** [comment]
[data.zip](https://github.com/lucasmansilla/Multi-Atlas_RCA/files/6947935/data.zip)
[1_affine.txt](https://github.com/lucasmansilla/Multi-Atlas_RCA/files/6947936/1_affine.txt)

Im just using your code for predicting the dice scores so my testing images have already been segmented.
@lucasmansilla

**Comment by lucasmansilla** [comment]
Hi @hdiggins,

I have seen that your dataset contains images of different sizes. To predict the Dice scores with this code you first need to look for the most similar images and the image similarity metrics that are included here operate with images of the same size. 

Have you solved this step in an alternative way?
